import { type NextPage } from "next";
import Head from "next/head";
import { useThemeContext } from "react-aria /context/ThemeContextProvider";

const Home: NextPage = () => {
  const { isDarkTheme, setIsDarkTheme } = useThemeContext();
  return (
    <>
      <Head>
        <title>ShopNest Admin</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={() => setIsDarkTheme(!isDarkTheme)}>
          Toggle Theme
        </button>
        <div className="">hello world</div>
      </main>
    </>
  );
};

export default Home;
